### ISSUE TITLE
Incompatibility with sylius 1.0

### ISSUE THREAD

**Issue by einorler** [webburza/sylius-wishlist-bundle#18]
Hi, @ychanan 

Nice to find a plugin for Sylius wishlists, unfortunately it seems to be incompatible with Sylius 1.0.
As I checked it is really missing very little for this compatibility, I already implemented the minor changes in my own fork and I will contribute the changes shortly, it would be great if you could check them out.

**Comment by ychanan** [comment]
Bundle has now converted to plugin, and upgraded to work with Sylius 1.1.*
