### ISSUE TITLE
Error when product don't have taxon.

### ISSUE THREAD

**Issue by kpitn** [webburza/sylius-wishlist-bundle#9]
When adding a product in wishlist, with product without taxon i have this error : 

`Impossible to access an attribute ("slug") on a null variable in @WebburzaSyliusWishlist/Frontend/Wishlist/_info.html.twig at line 6.`

Changing : 
`<a href="{{ path('sylius_shop_product_show', {'taxonSlug': product.mainTaxon.slug, 'id': product.id, 'slug': product.slug}) }}" class="sylius-product-name">{{ product.name }}</a>`

With : 
`<a href="{{ path('sylius_shop_product_show', {'id': product.id, 'slug': product.slug}) }}" class="sylius-product-name">{{ product.name }}</a>`

Fix the exception.

**Comment by ychanan** [comment]
Resolved in https://github.com/webburza/sylius-wishlist-bundle/pull/10/commits/422d2317b363786960e3dcffbd18dba5ec437c25 (v0.4.2).

Thanks.
